//! Generate the workspace `.cocli/bin/cocli` shell wrapper.
//!
//! The wrapper appends structured lines to `.cocli/audit.jsonl` before
//! forwarding to `cocli-bridge action`, giving daemon-rs a reliable activity
//! source that does not depend on parsing streamed thought/text.

use std::fmt::Write as _;
use std::path::Path;

use crate::embedded_manifest;

const WRAPPER_BODY: &str = r#"#!/bin/sh
# Generated by cocli-bridge-config; do not edit.
COCLI_ROOT="${COCLI_ACTION_ROOT:-$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)}"
AUDIT="${COCLI_ROOT}/audit.jsonl"
BRIDGE=__BRIDGE__

__TOOL_CASE__

_cocli_json_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

_cocli_audit_append() {
  _action="$1"
  _tool="$2"
  shift 2
  _ts=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u)
  _argv="["
  _first=1
  for _arg in "$@"; do
    _escaped=$(_cocli_json_escape "$_arg")
    if [ "$_first" = 1 ]; then _first=0; else _argv="${_argv},"; fi
    _argv="${_argv}\"${_escaped}\""
  done
  _argv="${_argv}]"
  printf '%s\n' "{\"ts\":\"${_ts}\",\"argv\":${_argv},\"action\":\"${_action}\",\"tool\":\"${_tool}\"}" >> "$AUDIT" 2>/dev/null || true
}

_cocli_resolve_action() {
  if [ "$#" -lt 1 ]; then
    return 1
  fi
  if [ "$1" = "action" ]; then
    if [ "$#" -lt 2 ]; then
      return 1
    fi
    _candidate="$2"
    case "$_candidate" in
      *.*)
        printf '%s' "$_candidate"
        return 0
        ;;
    esac
    if [ "$#" -lt 3 ]; then
      return 1
    fi
    printf '%s.%s' "$_candidate" "$3"
    return 0
  fi
  if [ "$#" -lt 2 ]; then
    return 1
  fi
  _verb="$2"
  case "$_verb" in
    set_work) _verb="set-work" ;;
    get_work) _verb="get-work" ;;
    clear_work) _verb="clear-work" ;;
    create_channel) _verb="create-channel" ;;
    add_dependency) _verb="add-dependency" ;;
    get_dependencies) _verb="get-dependencies" ;;
    update_status) _verb="update-status" ;;
  esac
  # Manifest action names use underscores (task.update_status); CLI verbs use
  # hyphens (update-status). Match bridge normalizeActionName for audit lookup.
  _action=$(printf '%s.%s' "$1" "$_verb" | sed 's/-/_/g')
  printf '%s' "$_action"
}

if [ "$#" -gt 0 ]; then
  _action=$(_cocli_resolve_action "$@" 2>/dev/null) || _action=""
  if [ -n "$_action" ]; then
    _tool=$(_cocli_tool_for_action "$_action")
    if [ -n "$_tool" ]; then
      _cocli_audit_append "$_action" "$_tool" "$@"
    fi
  fi
fi

exec "$BRIDGE" action "$@"
"#;

/// Build the injected `cocli` wrapper script for `work_dir/.cocli/bin/cocli`.
pub fn render_cocli_wrapper(bridge_binary: &Path) -> String {
    WRAPPER_BODY
        .replace(
            "__BRIDGE__",
            &shell_escape(bridge_binary.to_string_lossy().as_ref()),
        )
        .replace("__TOOL_CASE__", &render_tool_case())
}

fn render_tool_case() -> String {
    let mut out = String::from("_cocli_tool_for_action() {\n  case \"$1\" in\n");
    for cmd in &embedded_manifest().commands {
        let _ = writeln!(out, "    {}) printf '%s' \"{}\" ;;", cmd.action, cmd.tool);
    }
    out.push_str("    *) return 1 ;;\n  esac\n}\n");
    out
}

fn shell_escape(value: &str) -> String {
    let mut out = String::from('"');
    for ch in value.chars() {
        match ch {
            '"' | '\\' | '$' | '`' => {
                out.push('\\');
                out.push(ch);
            }
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn wrapper_embeds_bridge_path_and_audit_helpers() {
        let script = render_cocli_wrapper(Path::new("/opt/cocli/bin/cocli-bridge"));
        assert!(script.contains("#!/bin/sh"));
        assert!(script.contains("BRIDGE=\"/opt/cocli/bin/cocli-bridge\""));
        assert!(script.contains("audit.jsonl"));
        assert!(script.contains("_cocli_audit_append"));
        assert!(script.contains("message.send"));
        assert!(script.contains("send_message"));
        assert!(script.contains("exec \"$BRIDGE\" action \"$@\""));
    }
}
