use chrono::Utc;
use serde::{Deserialize, Serialize};
use sqlx_core::query::query;
use sqlx_core::query_scalar::query_scalar;
use sqlx_core::row::Row;
use uuid::Uuid;

use super::{Store, StoreError};

const MEMORY_INDEX_FILENAME: &str = "MEMORY.md";
const MEMORY_INDEX_HEADER: &str =
    "<!-- auto-generated by memory_write — do not edit manually -->\n";
const MAX_TOPIC_SLUG_LEN: usize = 60;
const MAX_DESCRIPTION_LEN: usize = 150;
const MAX_TOPIC_BODY_BYTES: usize = 64 * 1024;
const MAX_NAMESPACE_BYTES: i64 = 1024 * 1024;
const MAX_INDEX_LINES: usize = 200;

/// L1 agent-private or L2 channel-shared memory selector.
#[derive(Clone, Copy, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryScope {
    Agent,
    Channel,
}

/// Fully resolved local memory namespace.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MemoryNamespace {
    Agent(Uuid),
    Channel(Uuid),
}

impl MemoryNamespace {
    pub fn scope(self) -> MemoryScope {
        match self {
            Self::Agent(_) => MemoryScope::Agent,
            Self::Channel(_) => MemoryScope::Channel,
        }
    }

    pub fn id(self) -> Uuid {
        match self {
            Self::Agent(id) | Self::Channel(id) => id,
        }
    }

    pub fn prefix(self) -> String {
        match self {
            Self::Agent(id) => format!("agents/{id}/memory/"),
            Self::Channel(id) => format!("channels/{id}/notes/"),
        }
    }

    pub fn index_path(self) -> String {
        format!("{}{}", self.prefix(), MEMORY_INDEX_FILENAME)
    }

    pub fn topic_path(self, memory_type: &str, topic: &str) -> String {
        format!("{}{memory_type}_{topic}.md", self.prefix())
    }
}

/// Minimal body/version response used by existing Web memory panels.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MemoryDocument {
    pub body: String,
    pub version: i64,
}

/// Rich typed topic returned to local agents through the bridge.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MemoryTopic {
    #[serde(rename = "type")]
    pub memory_type: String,
    pub topic: String,
    pub description: String,
    pub updated: String,
    pub body: String,
    pub path: String,
    pub version: i64,
}

/// Canonical paths returned after an atomic memory move.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct MemoryMoveResult {
    pub from: String,
    pub to: String,
}

impl Store {
    /// Reads a namespace index, returning an empty document before first write.
    pub async fn get_memory_index(
        &self,
        namespace: MemoryNamespace,
    ) -> Result<MemoryDocument, StoreError> {
        Ok(
            match self.get_memory_document(&namespace.index_path()).await? {
                Some(page) => MemoryDocument {
                    body: page.content,
                    version: page.version,
                },
                None => MemoryDocument {
                    body: String::new(),
                    version: 0,
                },
            },
        )
    }

    /// Reads one validated typed memory topic.
    pub async fn get_memory_topic(
        &self,
        namespace: MemoryNamespace,
        memory_type: &str,
        topic: &str,
    ) -> Result<Option<MemoryTopic>, StoreError> {
        validate_memory_type(memory_type)?;
        validate_topic_slug(topic)?;
        self.get_memory_document(&namespace.topic_path(memory_type, topic))
            .await?
            .map(|page| memory_topic_from_page(page, memory_type, topic))
            .transpose()
    }

    /// Lists all durable pages in a memory namespace for workspace mirroring.
    pub async fn list_memory_namespace(
        &self,
        namespace: MemoryNamespace,
    ) -> Result<Vec<MemoryDocumentEntry>, StoreError> {
        self.list_memory_documents_by_prefix(&namespace.prefix())
            .await
            .map(|pages| {
                pages
                    .into_iter()
                    .map(|page| MemoryDocumentEntry {
                        path: page.path,
                        body: page.content,
                        version: page.version,
                    })
                    .collect()
            })
    }

    /// Atomically writes a topic and regenerates the namespace index.
    #[allow(clippy::too_many_arguments)]
    pub async fn write_memory_topic(
        &self,
        namespace: MemoryNamespace,
        memory_type: &str,
        topic: &str,
        description: &str,
        body: &str,
        updated_by: Option<&str>,
        if_version: Option<i64>,
    ) -> Result<MemoryTopic, StoreError> {
        validate_memory_type(memory_type)?;
        validate_topic_slug(topic)?;
        validate_description(description)?;
        if body.len() > MAX_TOPIC_BODY_BYTES {
            return Err(StoreError::MemoryTopicTooLarge {
                bytes: body.len(),
                limit: MAX_TOPIC_BODY_BYTES,
            });
        }

        let updated = Utc::now().format("%Y-%m-%d").to_string();
        let content = render_topic_content(description, memory_type, &updated, body);
        let topic_path = namespace.topic_path(memory_type, topic);
        let mut transaction = self.pool.begin().await?;
        let page = upsert_memory_document_in_transaction(
            &mut transaction,
            &topic_path,
            &content,
            updated_by,
            if_version,
        )
        .await?;
        enforce_namespace_size(&mut transaction, &namespace.prefix()).await?;
        regenerate_memory_index(&mut transaction, namespace, updated_by).await?;
        enforce_namespace_size(&mut transaction, &namespace.prefix()).await?;
        transaction.commit().await?;
        Ok(MemoryTopic {
            memory_type: memory_type.to_owned(),
            topic: topic.to_owned(),
            description: description.to_owned(),
            updated,
            body: content,
            path: topic_path,
            version: page.version,
        })
    }

    /// Atomically moves one topic and regenerates both namespace indexes.
    pub async fn move_memory_topic(
        &self,
        from: MemoryNamespace,
        to: MemoryNamespace,
        memory_type: &str,
        topic: &str,
        updated_by: Option<&str>,
    ) -> Result<MemoryMoveResult, StoreError> {
        validate_memory_type(memory_type)?;
        validate_topic_slug(topic)?;
        if from == to {
            return Err(StoreError::MemoryMoveSameNamespace);
        }
        let from_path = from.topic_path(memory_type, topic);
        let to_path = to.topic_path(memory_type, topic);
        let mut transaction = self.pool.begin().await?;
        let source_content: String =
            query_scalar("SELECT content_md FROM memory_documents WHERE path = ?")
                .bind(&from_path)
                .fetch_optional(&mut *transaction)
                .await?
                .ok_or_else(|| StoreError::MemoryTopicNotFound(from_path.clone()))?;
        let frontmatter = parse_memory_frontmatter(&source_content);
        let updated = Utc::now().format("%Y-%m-%d").to_string();
        let content = render_topic_content(
            &frontmatter.description,
            memory_type,
            &updated,
            &frontmatter.body,
        );

        upsert_memory_document_in_transaction(
            &mut transaction,
            &to_path,
            &content,
            updated_by,
            None,
        )
        .await?;
        query("DELETE FROM memory_documents WHERE path = ?")
            .bind(&from_path)
            .execute(&mut *transaction)
            .await?;
        regenerate_memory_index(&mut transaction, from, updated_by).await?;
        regenerate_memory_index(&mut transaction, to, updated_by).await?;
        enforce_namespace_size(&mut transaction, &from.prefix()).await?;
        enforce_namespace_size(&mut transaction, &to.prefix()).await?;
        transaction.commit().await?;
        Ok(MemoryMoveResult {
            from: from_path,
            to: to_path,
        })
    }
}

/// One page used to materialize a runtime workspace mirror.
#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MemoryDocumentEntry {
    pub path: String,
    pub body: String,
    pub version: i64,
}

#[derive(Clone, Debug)]
struct MemoryRecord {
    path: String,
    content: String,
    version: i64,
}

impl Store {
    async fn get_memory_document(&self, path: &str) -> Result<Option<MemoryRecord>, StoreError> {
        let row = query("SELECT path, content_md, version FROM memory_documents WHERE path = ?")
            .bind(path)
            .fetch_optional(&self.pool)
            .await?;
        row.map(memory_record_from_row).transpose()
    }

    async fn list_memory_documents_by_prefix(
        &self,
        prefix: &str,
    ) -> Result<Vec<MemoryRecord>, StoreError> {
        let rows = query(
            "SELECT path, content_md, version FROM memory_documents \
             WHERE path LIKE ? ORDER BY path",
        )
        .bind(format!("{prefix}%"))
        .fetch_all(&self.pool)
        .await?;
        rows.into_iter().map(memory_record_from_row).collect()
    }
}

fn memory_record_from_row(row: sqlx_sqlite::SqliteRow) -> Result<MemoryRecord, StoreError> {
    Ok(MemoryRecord {
        path: row.try_get("path")?,
        content: row.try_get("content_md")?,
        version: row.try_get("version")?,
    })
}

async fn upsert_memory_document_in_transaction(
    transaction: &mut sqlx_core::transaction::Transaction<'_, sqlx_sqlite::Sqlite>,
    path: &str,
    content: &str,
    updated_by: Option<&str>,
    if_version: Option<i64>,
) -> Result<MemoryRecord, StoreError> {
    let now = Utc::now();
    let existing = query("SELECT id, version FROM memory_documents WHERE path = ?")
        .bind(path)
        .fetch_optional(&mut **transaction)
        .await?;
    let version = if let Some(existing) = existing {
        let id: Uuid = existing.try_get("id")?;
        let current_version: i64 = existing.try_get("version")?;
        if let Some(attempted_version) = if_version.filter(|version| *version > 0) {
            if attempted_version != current_version {
                return Err(StoreError::MemoryVersionConflict {
                    path: path.to_owned(),
                    current_version,
                    attempted_version,
                });
            }
        }
        let version = current_version + 1;
        query(
            "UPDATE memory_documents SET content_md = ?, version = ?, updated_at = ?, \
             updated_by = ? WHERE id = ?",
        )
        .bind(content)
        .bind(version)
        .bind(now)
        .bind(updated_by)
        .bind(id)
        .execute(&mut **transaction)
        .await?;
        version
    } else {
        query(
            "INSERT INTO memory_documents \
             (id, path, content_md, version, created_at, updated_at, updated_by) \
             VALUES (?, ?, ?, 1, ?, ?, ?)",
        )
        .bind(Uuid::new_v4())
        .bind(path)
        .bind(content)
        .bind(now)
        .bind(now)
        .bind(updated_by)
        .execute(&mut **transaction)
        .await?;
        1
    };
    Ok(MemoryRecord {
        path: path.to_owned(),
        content: content.to_owned(),
        version,
    })
}

async fn regenerate_memory_index(
    transaction: &mut sqlx_core::transaction::Transaction<'_, sqlx_sqlite::Sqlite>,
    namespace: MemoryNamespace,
    updated_by: Option<&str>,
) -> Result<MemoryRecord, StoreError> {
    let prefix = namespace.prefix();
    let index_path = namespace.index_path();
    let rows = query(
        "SELECT path, content_md FROM memory_documents \
         WHERE path LIKE ? AND path != ? ORDER BY path",
    )
    .bind(format!("{prefix}%"))
    .bind(&index_path)
    .fetch_all(&mut **transaction)
    .await?;
    let mut entries = rows
        .into_iter()
        .map(|row| {
            let path: String = row.try_get("path")?;
            let content: String = row.try_get("content_md")?;
            let frontmatter = parse_memory_frontmatter(&content);
            let filename = path
                .strip_prefix(&prefix)
                .unwrap_or(path.as_str())
                .to_owned();
            Ok(IndexEntry {
                filename,
                description: frontmatter.description,
                updated: frontmatter.updated,
            })
        })
        .collect::<Result<Vec<_>, StoreError>>()?;
    entries.sort_by(|left, right| {
        right
            .updated
            .cmp(&left.updated)
            .then_with(|| left.filename.cmp(&right.filename))
    });
    let mut body = MEMORY_INDEX_HEADER.to_owned();
    for entry in entries {
        let slug = entry.filename.trim_end_matches(".md");
        body.push_str(&format!(
            "- [{slug}]({}) — {}\n",
            entry.filename, entry.description
        ));
    }
    let lines = body.lines().count();
    if lines > MAX_INDEX_LINES {
        return Err(StoreError::MemoryIndexFull {
            lines,
            limit: MAX_INDEX_LINES,
        });
    }
    upsert_memory_document_in_transaction(transaction, &index_path, &body, updated_by, None).await
}

async fn enforce_namespace_size(
    transaction: &mut sqlx_core::transaction::Transaction<'_, sqlx_sqlite::Sqlite>,
    prefix: &str,
) -> Result<(), StoreError> {
    let bytes: i64 = query_scalar(
        "SELECT COALESCE(SUM(LENGTH(CAST(content_md AS BLOB))), 0) \
         FROM memory_documents WHERE path LIKE ?",
    )
    .bind(format!("{prefix}%"))
    .fetch_one(&mut **transaction)
    .await?;
    if bytes > MAX_NAMESPACE_BYTES {
        return Err(StoreError::MemoryNamespaceFull {
            bytes,
            limit: MAX_NAMESPACE_BYTES,
        });
    }
    Ok(())
}

fn memory_topic_from_page(
    page: MemoryRecord,
    memory_type: &str,
    topic: &str,
) -> Result<MemoryTopic, StoreError> {
    let frontmatter = parse_memory_frontmatter(&page.content);
    Ok(MemoryTopic {
        memory_type: memory_type.to_owned(),
        topic: topic.to_owned(),
        description: frontmatter.description,
        updated: frontmatter.updated,
        body: page.content,
        path: page.path,
        version: page.version,
    })
}

fn validate_memory_type(memory_type: &str) -> Result<(), StoreError> {
    if matches!(memory_type, "user" | "feedback" | "project" | "reference") {
        Ok(())
    } else {
        Err(StoreError::InvalidMemoryType(memory_type.to_owned()))
    }
}

fn validate_topic_slug(topic: &str) -> Result<(), StoreError> {
    if topic.is_empty()
        || topic.len() > MAX_TOPIC_SLUG_LEN
        || !topic
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
    {
        Err(StoreError::InvalidMemoryTopic(topic.to_owned()))
    } else {
        Ok(())
    }
}

fn validate_description(description: &str) -> Result<(), StoreError> {
    if description.chars().count() > MAX_DESCRIPTION_LEN {
        return Err(StoreError::InvalidMemoryDescription(
            "description exceeds 150 characters".to_owned(),
        ));
    }
    if description
        .chars()
        .any(|character| matches!(character, '\r' | '\n'))
    {
        return Err(StoreError::InvalidMemoryDescription(
            "description must be one line".to_owned(),
        ));
    }
    Ok(())
}

fn render_topic_content(description: &str, memory_type: &str, updated: &str, body: &str) -> String {
    format!(
        "---\ndescription: {description}\ntype: {memory_type}\nupdated: {updated}\n---\n\n{body}"
    )
}

struct ParsedMemory {
    description: String,
    updated: String,
    body: String,
}

fn parse_memory_frontmatter(content: &str) -> ParsedMemory {
    let mut parsed = ParsedMemory {
        description: "(no description)".to_owned(),
        updated: String::new(),
        body: content.to_owned(),
    };
    let Some(rest) = content.strip_prefix("---\n") else {
        return parsed;
    };
    let Some(close) = rest.find("\n---\n") else {
        return parsed;
    };
    for line in rest[..close].lines() {
        if let Some(value) = line.strip_prefix("description:") {
            value.trim().clone_into(&mut parsed.description);
        } else if let Some(value) = line.strip_prefix("updated:") {
            value.trim().clone_into(&mut parsed.updated);
        }
    }
    rest[close + "\n---\n".len()..]
        .trim_start_matches('\n')
        .clone_into(&mut parsed.body);
    parsed
}

struct IndexEntry {
    filename: String,
    description: String,
    updated: String,
}

#[cfg(test)]
mod tests {
    use super::{parse_memory_frontmatter, render_topic_content};

    #[test]
    fn frontmatter_round_trips_body_and_index_fields() {
        let content = render_topic_content("Apollo plan", "project", "2026-07-16", "# Body");
        let parsed = parse_memory_frontmatter(&content);
        assert_eq!(parsed.description, "Apollo plan");
        assert_eq!(parsed.updated, "2026-07-16");
        assert_eq!(parsed.body, "# Body");
    }
}
