export type LocalLanguage = 'en' | 'zh-CN'

export const LANGUAGE_OPTIONS = [
  { value: 'en', label: 'English', meta: 'EN' },
  { value: 'zh-CN', label: '简体中文', meta: '中' },
] as const

const english = {
  loading: 'Starting local workspace…',
  brand: 'cocli local',
  serviceOnline: 'SQLite + HTTP online',
  workspaceNavigation: 'Workspace navigation',
  chatWorkspace: 'Chat',
  tasksWorkspace: 'Tasks',
  skillsWorkspace: 'Skills',
  dismiss: 'Dismiss',
  close: 'Close',
  refresh: 'Refresh',
  channelsAndRuntimes: 'Channels and runtimes',
  channels: 'Channels',
  channelsNav: 'Channels',
  noChannels: 'Create a channel to open your first local workspace.',
  newChannel: 'New channel',
  channelPlaceholder: 'product-loop',
  add: 'Add',
  runtimes: 'Local runtimes',
  installed: 'installed',
  unavailable: 'unavailable',
  noRuntimes: 'No runtime catalog is configured.',
  conversation: 'Channel conversation',
  localChannel: 'LOCAL CHANNEL',
  chooseChannel: 'Choose a channel',
  agentCount: '{{count}} agent',
  agentCountPlural: '{{count}} agents',
  createChannel: 'Create a channel',
  createChannelDescription: 'Your channels, agents, and message history stay in the local SQLite database.',
  loadingMessages: 'Loading message history…',
  startTask: 'Start a real task',
  startTaskDescription: 'Add an installed runtime agent, then send a concrete prompt from the composer below.',
  you: 'you',
  agent: 'agent',
  taskFor: 'Task for #{{channel}}',
  selectChannelFirst: 'Select a channel first',
  taskPlaceholder: 'Describe the task, constraints, and expected result…',
  runningAgentsHint: 'Running agents will receive this task.',
  noRunningAgentHint: 'Add or start an agent before sending.',
  running: 'Running…',
  runTask: 'Run task',
  channelAgents: 'Channel agents',
  agents: 'Agents',
  runtime: 'runtime',
  model: 'model',
  state: 'state',
  defaultModel: 'default',
  stopDelivery: 'Stop delivery',
  startAgent: 'Start agent',
  noAgents: 'No agent is attached to this channel yet.',
  addAgent: 'Add agent',
  name: 'Name',
  agentPlaceholder: 'builder',
  runtimeLabel: 'Runtime',
  noRuntimeInstalled: 'No runtime installed',
  modelLabel: 'Model',
  runtimeDefault: 'runtime default',
  adding: 'Adding…',
  addRunningAgent: 'Add running agent',
  language: 'Language',
  appearance: 'Appearance',
  lightMode: 'Light',
  darkMode: 'Dark',
  selectOption: 'Select an option',
  tasksEyebrow: 'LOCAL EXECUTION PLAN',
  tasksTitle: 'Task board',
  tasksDescription: 'Plan channel work, assign local Agents, track progress, and keep dependencies explicit.',
  tasksChannel: 'Channel',
  tasksSelectChannel: 'Select a channel',
  tasksFilter: 'Filter tasks',
  tasksFilterPlaceholder: 'Number, title, status, progress, or assignee',
  tasksView: 'Task view',
  tasksBoardView: 'Board',
  tasksListView: 'List',
  tasksNewTask: 'New task',
  tasksTitlePlaceholder: 'Describe a concrete deliverable',
  tasksCreating: 'Creating…',
  tasksCreate: 'Create task',
  tasksNoChannel: 'Create a channel first',
  tasksNoChannelDescription: 'Tasks are scoped to one local conversation channel.',
  tasksLoading: 'Loading channel tasks and dependencies…',
  tasksEmpty: 'No tasks yet',
  tasksEmptyDescription: 'Create the first task to make the local execution plan visible.',
  tasksNoMatches: 'No matching tasks',
  tasksNoMatchesDescription: 'Clear or change the filter to show other channel tasks.',
  tasksNoStatusTasks: 'No tasks in this state',
  tasksUnassigned: 'unassigned',
  tasksBlockedBy: 'blocked by #{{tasks}}',
  tasksDetail: 'Task detail',
  tasksStatus: 'Status',
  tasksStatusTodo: 'Todo',
  tasksStatusInProgress: 'In progress',
  tasksStatusInReview: 'In review',
  tasksStatusDone: 'Done',
  tasksAssignee: 'Assignee',
  tasksUnclaim: 'Unclaim',
  tasksSelectAgent: 'Select an Agent',
  tasksClaim: 'Claim task',
  tasksNoAgents: 'Add an Agent to this channel before assigning work.',
  tasksProgress: 'Progress',
  tasksProgressPlaceholder: 'Record the latest result, blocker, or next step.',
  tasksSaveProgress: 'Save progress',
  tasksDependencies: 'Dependencies',
  tasksUnknownDependency: 'Unknown task',
  tasksRemoveDependency: 'Remove dependency #{{task}}',
  tasksSelectDependency: 'Select a prerequisite',
  tasksAddDependency: 'Add dependency',
  tasksCreated: 'Created',
  tasksLoadError: 'Unable to load local tasks.',
  tasksActionError: 'Task operation failed.',
  skillsEyebrow: 'LOCAL CAPABILITY REGISTRY',
  skillsTitle: 'Skills workspace',
  skillsDescription: 'Import reusable skill folders once, then install them atomically into any local Agent workspace.',
  skillsCatalog: 'Local catalog',
  skillsCatalogDescription: 'SQLite is the source of truth for imported skill snapshots.',
  skillsSource: 'Source URL or absolute path',
  skillsSourcePlaceholder: '/Users/me/skills/reviewer or https://github.com/org/repo.git',
  skillsSubpath: 'Subpath (optional)',
  skillsSubpathPlaceholder: 'skills/reviewer',
  skillsNameOverride: 'Name override (optional)',
  skillsNamePlaceholder: 'reviewer',
  skillsImport: 'Import skill',
  skillsImporting: 'Importing…',
  skillsLoadingCatalog: 'Loading local skill catalog…',
  skillsEmptyCatalog: 'No skills imported',
  skillsEmptyCatalogDescription: 'Import a folder with SKILL.md to build the reusable local catalog.',
  skillsNoDescription: 'No description in SKILL.md.',
  skillsFiles: 'Files',
  skillsSize: 'Size',
  skillsInUse: 'In use',
  skillsReinstall: 'Refresh',
  skillsInstall: 'Install',
  skillsInstalled: 'Installed',
  skillsDelete: 'Delete skill',
  skillsDeleteConfirm: 'Delete {{name}} from the local catalog and remove its managed installs?',
  skillsAgentWorkspace: 'Agent workspace',
  skillsAgentWorkspaceDescription: 'Compare runtime discovery with managed SQLite install records.',
  skillsAgent: 'Agent',
  skillsSelectAgent: 'Select an Agent',
  skillsCompatibilitySupported: 'supported',
  skillsCompatibilityUncertain: 'experimental',
  skillsCompatibilityUnsupported: 'unsupported',
  skillsCompatibilityUnknown: 'unknown',
  skillsNoAgent: 'Add an Agent first',
  skillsNoAgentDescription: 'Skills are installed into a specific local Agent workspace.',
  skillsLoadingAgent: 'Scanning runtime skill paths…',
  skillsEmptyAgent: 'No skills discovered',
  skillsEmptyAgentDescription: 'Import a catalog entry and install it, or add a runtime-native skill on disk.',
  skillsFilter: 'Filter Agent skills',
  skillsFilterPlaceholder: 'Name, state, type, or description',
  skillsNoMatches: 'No matching skills',
  skillsNoMatchesDescription: 'Clear or change the filter to show other discovered skills.',
  skillsViewFiles: 'View files',
  skillsRemoveRecord: 'Remove record',
  skillsUninstall: 'Uninstall',
  skillsFileBrowser: 'INSTALLED FILES',
  skillsBinaryFile: 'Binary file preview is not available.',
  skillsSelectFile: 'Select a text file to preview.',
  skillsSelectedLibrary: 'Selected catalog entry',
  skillsInstallTo: 'Install to {{agent}}',
  skillsLoadError: 'Unable to load local skills.',
  skillsActionError: 'Skill operation failed.',
}

const chinese: Record<keyof typeof english, string> = {
  loading: '正在启动本地工作区…',
  brand: 'cocli 本地',
  serviceOnline: 'SQLite + HTTP 已连接',
  workspaceNavigation: '工作区导航',
  chatWorkspace: '对话',
  tasksWorkspace: '任务',
  skillsWorkspace: 'Skills',
  dismiss: '关闭',
  close: '关闭',
  refresh: '刷新',
  channelsAndRuntimes: '频道与运行时',
  channels: '频道',
  channelsNav: '频道',
  noChannels: '创建一个频道，开启首个本地工作区。',
  newChannel: '新建频道',
  channelPlaceholder: 'product-loop',
  add: '添加',
  runtimes: '本地运行时',
  installed: '已安装',
  unavailable: '不可用',
  noRuntimes: '尚未配置运行时目录。',
  conversation: '频道对话',
  localChannel: '本地频道',
  chooseChannel: '选择一个频道',
  agentCount: '{{count}} 个 Agent',
  agentCountPlural: '{{count}} 个 Agent',
  createChannel: '创建频道',
  createChannelDescription: '频道、Agent 和消息记录会保存在本机 SQLite 数据库中。',
  loadingMessages: '正在加载消息记录…',
  startTask: '开始真实任务',
  startTaskDescription: '添加一个已安装的运行时 Agent，然后在下方输入明确任务。',
  you: '你',
  agent: 'Agent',
  taskFor: '#{{channel}} 的任务',
  selectChannelFirst: '请先选择频道',
  taskPlaceholder: '描述任务、约束条件和预期结果…',
  runningAgentsHint: '运行中的 Agent 将收到此任务。',
  noRunningAgentHint: '请先添加或启动一个 Agent。',
  running: '执行中…',
  runTask: '运行任务',
  channelAgents: '频道 Agent',
  agents: 'Agent',
  runtime: '运行时',
  model: '模型',
  state: '状态',
  defaultModel: '默认',
  stopDelivery: '停止接收',
  startAgent: '启动 Agent',
  noAgents: '此频道还没有关联 Agent。',
  addAgent: '添加 Agent',
  name: '名称',
  agentPlaceholder: 'builder',
  runtimeLabel: '运行时',
  noRuntimeInstalled: '没有已安装的运行时',
  modelLabel: '模型',
  runtimeDefault: '运行时默认值',
  adding: '添加中…',
  addRunningAgent: '添加并启动 Agent',
  language: '语言',
  appearance: '外观',
  lightMode: '亮色',
  darkMode: '暗色',
  selectOption: '选择一个选项',
  tasksEyebrow: '本地执行计划',
  tasksTitle: '任务看板',
  tasksDescription: '规划频道工作、分配本地 Agent、记录进度，并明确维护任务依赖。',
  tasksChannel: '频道',
  tasksSelectChannel: '选择频道',
  tasksFilter: '筛选任务',
  tasksFilterPlaceholder: '编号、标题、状态、进度或负责人',
  tasksView: '任务视图',
  tasksBoardView: '看板',
  tasksListView: '列表',
  tasksNewTask: '新建任务',
  tasksTitlePlaceholder: '描述一个明确的交付结果',
  tasksCreating: '创建中…',
  tasksCreate: '创建任务',
  tasksNoChannel: '请先创建频道',
  tasksNoChannelDescription: '任务归属于一个本地对话频道。',
  tasksLoading: '正在加载频道任务与依赖…',
  tasksEmpty: '还没有任务',
  tasksEmptyDescription: '创建首个任务，让本地执行计划清晰可见。',
  tasksNoMatches: '没有匹配的任务',
  tasksNoMatchesDescription: '清空或调整筛选条件以查看其他频道任务。',
  tasksNoStatusTasks: '此状态下没有任务',
  tasksUnassigned: '未分配',
  tasksBlockedBy: '被 #{{tasks}} 阻塞',
  tasksDetail: '任务详情',
  tasksStatus: '状态',
  tasksStatusTodo: '待办',
  tasksStatusInProgress: '进行中',
  tasksStatusInReview: '审核中',
  tasksStatusDone: '完成',
  tasksAssignee: '负责人',
  tasksUnclaim: '取消认领',
  tasksSelectAgent: '选择 Agent',
  tasksClaim: '认领任务',
  tasksNoAgents: '请先向此频道添加 Agent，再分配任务。',
  tasksProgress: '进度',
  tasksProgressPlaceholder: '记录最新结果、阻塞项或下一步。',
  tasksSaveProgress: '保存进度',
  tasksDependencies: '依赖任务',
  tasksUnknownDependency: '未知任务',
  tasksRemoveDependency: '移除依赖 #{{task}}',
  tasksSelectDependency: '选择前置任务',
  tasksAddDependency: '添加依赖',
  tasksCreated: '创建时间',
  tasksLoadError: '无法加载本地任务。',
  tasksActionError: '任务操作失败。',
  skillsEyebrow: '本地能力目录',
  skillsTitle: 'Skills 工作区',
  skillsDescription: 'Skill 目录只需导入一次，即可原子安装到任意本地 Agent 工作区。',
  skillsCatalog: '本地目录',
  skillsCatalogDescription: 'SQLite 保存导入 Skill 的权威快照。',
  skillsSource: '来源 URL 或绝对路径',
  skillsSourcePlaceholder: '/Users/me/skills/reviewer 或 https://github.com/org/repo.git',
  skillsSubpath: '子目录（可选）',
  skillsSubpathPlaceholder: 'skills/reviewer',
  skillsNameOverride: '名称覆盖（可选）',
  skillsNamePlaceholder: 'reviewer',
  skillsImport: '导入 Skill',
  skillsImporting: '导入中…',
  skillsLoadingCatalog: '正在加载本地 Skill 目录…',
  skillsEmptyCatalog: '尚未导入 Skill',
  skillsEmptyCatalogDescription: '导入包含 SKILL.md 的目录，建立可复用的本地能力目录。',
  skillsNoDescription: 'SKILL.md 中没有描述。',
  skillsFiles: '文件',
  skillsSize: '大小',
  skillsInUse: '使用中',
  skillsReinstall: '刷新',
  skillsInstall: '安装',
  skillsInstalled: '已安装',
  skillsDelete: '删除 Skill',
  skillsDeleteConfirm: '从本地目录删除 {{name}}，并移除其受管安装吗？',
  skillsAgentWorkspace: 'Agent 工作区',
  skillsAgentWorkspaceDescription: '对照运行时扫描结果与 SQLite 受管安装记录。',
  skillsAgent: 'Agent',
  skillsSelectAgent: '选择 Agent',
  skillsCompatibilitySupported: '支持',
  skillsCompatibilityUncertain: '实验性',
  skillsCompatibilityUnsupported: '不支持',
  skillsCompatibilityUnknown: '未知',
  skillsNoAgent: '请先添加 Agent',
  skillsNoAgentDescription: 'Skill 会安装到指定的本地 Agent 工作区。',
  skillsLoadingAgent: '正在扫描运行时 Skill 路径…',
  skillsEmptyAgent: '未发现 Skill',
  skillsEmptyAgentDescription: '可导入目录条目并安装，或直接在磁盘添加运行时原生 Skill。',
  skillsFilter: '筛选 Agent Skills',
  skillsFilterPlaceholder: '名称、状态、类型或描述',
  skillsNoMatches: '没有匹配的 Skill',
  skillsNoMatchesDescription: '清空或调整筛选条件以查看其他已发现的 Skill。',
  skillsViewFiles: '查看文件',
  skillsRemoveRecord: '移除记录',
  skillsUninstall: '卸载',
  skillsFileBrowser: '已安装文件',
  skillsBinaryFile: '暂不支持预览二进制文件。',
  skillsSelectFile: '请选择一个文本文件进行预览。',
  skillsSelectedLibrary: '已选目录条目',
  skillsInstallTo: '安装到 {{agent}}',
  skillsLoadError: '无法加载本地 Skills。',
  skillsActionError: 'Skill 操作失败。',
}

const dictionaries = {
  en: english,
  'zh-CN': chinese,
}

export type LocalCopyKey = keyof typeof english

export function translate(
  language: LocalLanguage,
  key: LocalCopyKey,
  values: Record<string, string | number> = {},
): string {
  let copy: string = dictionaries[language][key]
  for (const [name, value] of Object.entries(values)) {
    copy = copy.replaceAll(`{{${name}}}`, String(value))
  }
  return copy
}

export function resolveInitialLanguage(): LocalLanguage {
  try {
    const stored = localStorage.getItem('cocli-local-language')
    if (stored === 'en' || stored === 'zh-CN') return stored
  } catch {
    // Storage can be unavailable in privacy-restricted environments.
  }
  return navigator.language.toLowerCase().startsWith('zh') ? 'zh-CN' : 'en'
}
