export type LocalLanguage = 'en' | 'zh-CN'

export const LANGUAGE_OPTIONS = [
  { value: 'en', label: 'English', meta: 'EN' },
  { value: 'zh-CN', label: '简体中文', meta: '中' },
] as const

const english = {
  loading: 'Starting local workspace…',
  brand: 'cocli local',
  serviceOnline: 'SQLite + HTTP online',
  liveConnected: 'Live execution connected',
  liveReconnecting: 'Live execution reconnecting',
  onboardingEyebrow: 'FIRST RUN',
  onboardingTitle: 'Set up your first local task',
  onboardingDescription: 'cocli connects local runtimes, channels, and Agents without taking over their decisions.',
  onboardingRuntime: 'Detect an installed runtime',
  onboardingChannel: 'Create or select a channel',
  onboardingAgent: 'Add an Agent to this channel',
  onboardingTask: 'Send the first concrete task',
  liveRunning: 'LIVE',
  liveLimited: 'RATE LIMITED',
  liveError: 'ERROR',
  liveTool: 'tool',
  liveCancel: 'Cancel turn',
  liveCancelling: 'Cancelling…',
  search: 'Search',
  searching: 'Searching…',
  globalSearchEyebrow: 'LOCAL INDEX',
  globalSearch: 'Global search',
  globalSearchPlaceholder: 'Search channels, agents, messages, and tasks…',
  globalSearchEmpty: 'No matching local results.',
  downloadBackup: 'Download application-state backup',
  workspaceNavigation: 'Workspace navigation',
  channelWorkspace: 'Channel workspace',
  agentWorkspace: 'Agent workspace',
  agentOverview: 'Agent overview',
  agentSelect: 'Select an Agent',
  agentDirect: 'Direct conversation',
  agentNoMessages: 'Send this Agent a requirement to begin durable work.',
  agentDirectPlaceholder: 'Describe the requirement for this Agent…',
  currentWork: 'Current work',
  agentIdle: 'No current work anchor.',
  nextStep: 'Next step',
  memberChannels: 'Channels',
  workspaceAttachments: 'Workspace attachments',
  noWorkspaces: 'No optional Workspace is attached.',
  workspaceKind: 'Workspace kind',
  workspaceDirectory: 'Directory',
  workspaceGit: 'Git repository',
  workspaceExternal: 'External reference',
  workspaceManaged: 'Managed workspace',
  workspaceLocator: 'Workspace location',
  channelWorkspaceLocator: 'Channel Workspace location',
  workspaceLocatorPlaceholder: 'Path, repository, or external reference',
  attachWorkspace: 'Attach Workspace',
  operationHistory: 'Agent-created changes',
  noOperations: 'No self-organization operations recorded.',
  lifecycle: 'Lifecycle',
  diagnostics: 'Diagnostics',
  createStandaloneAgent: 'Create persistent Agent',
  description: 'Description',
  instructions: 'Instructions',
  agentDescriptionPlaceholder: 'What this Agent is responsible for',
  agentInstructionsPlaceholder: 'Durable operating instructions for this Agent',
  settings: 'Settings',
  runtimeSettings: 'Runtime settings',
  runtimeSettingsDescription: 'Runtime availability, versions, and capabilities are advanced execution details.',
  chatWorkspace: 'Chat',
  tasksWorkspace: 'Tasks',
  knowledgeWorkspace: 'Knowledge',
  historyWorkspace: 'History',
  skillsWorkspace: 'Skills',
  mcpWorkspace: 'MCP',
  mcpEyebrow: 'READ-ONLY GOVERNANCE',
  mcpTitle: 'MCP inventory and doctor',
  mcpDescription: 'Compare configured MCP definitions with Runtime-native evidence without changing local configuration.',
  mcpLoading: 'Inspecting local Runtime MCP state…',
  mcpLoadError: 'Unable to inspect local MCP state.',
  mcpDoctorStatus: 'Doctor status',
  mcpServers: 'Servers',
  mcpObservations: 'Observations',
  mcpFindings: 'Findings',
  mcpMatrix: 'Runtime × Server matrix',
  mcpMatrixDescription: 'D discoverable · C configured · L loaded · E enabled · P approved · A authenticated · H healthy · S current-session visible · I invoked. A dot means unknown, not false.',
  mcpRuntime: 'Runtime',
  mcpNotObserved: 'No observation for this Runtime and server.',
  mcpEvidence: 'Evidence and observation time',
  mcpEvidenceDescription: 'Native CLI/app-server evidence is kept separate from filesystem configuration discovery.',
  mcpNoFindings: 'No MCP doctor findings.',
  mcpZeroWriteNotice: 'Phase 2C applies only valid approvals through negotiated adapters, isolated writers, durable journal recovery, and fresh verification. Active Runtime sessions are not restarted.',
  mcpCapabilities: 'Runtime adapter capabilities',
  mcpCapabilitiesDescription: 'Versioned adapter contracts explain read/write/reload/verify support before a plan can be approved or applied.',
  mcpCapabilityHash: 'Capability hash',
  mcpAdapter: 'Adapter',
  mcpBinaryVersion: 'Binary/schema version',
  mcpReloadStrategy: 'Reload strategy',
  mcpDestination: 'Destination',
  mcpOperations: 'Operations',
  mcpNoCapabilities: 'No Runtime adapter capability report is available.',
  mcpProfiles: 'Profiles',
  mcpProfilesDescription: 'Versioned desired state bound to machine, Workspace, or Agent targets.',
  mcpNoProfiles: 'No MCP profiles are defined.',
  mcpProfileServers: 'servers',
  mcpNoBindings: 'No target bindings',
  mcpDesiredEnabled: 'desired enabled',
  mcpDesiredDisabled: 'desired disabled',
  mcpEffectiveDesired: 'Effective desired state',
  mcpEffectiveDescription: 'Resolved profile inheritance, conflicts, and winning bindings for this target.',
  mcpEffectiveTarget: 'Target',
  mcpConflicts: 'Conflicts',
  mcpHighRiskContext: 'high-risk context',
  mcpStandardContext: 'standard context',
  mcpAppliedResolution: 'applied',
  mcpSkippedResolution: 'skipped',
  mcpNoEffectiveDesired: 'No effective desired state is available.',
  mcpPlanPreview: 'Plan Preview',
  mcpPlanDescription: 'Preview the approved apply contract before Runtime writers touch isolated configuration sources.',
  mcpPlanning: 'Generating…',
  mcpGeneratePlan: 'Generate dry-run plan',
  mcpPlanError: 'MCP planning operation failed.',
  mcpApplyError: 'MCP apply operation failed.',
  mcpRollbackError: 'MCP rollback operation failed.',
  mcpApprovalStatus: 'Approval status',
  mcpApprovalExpires: 'Approval expires',
  mcpPlanHash: 'Plan hash',
  mcpDryRun: 'dry-run',
  mcpNotDryRun: 'not dry-run',
  mcpApprovedNotApplied: 'approved but not applied',
  mcpBlocked: 'blocked',
  mcpBefore: 'Before',
  mcpAfter: 'After',
  mcpExpectedHashes: 'Expected source/schema hash',
  mcpExecution: 'Execution',
  mcpExecutableAction: 'eligible for apply',
  mcpNonExecutableAction: 'not executed by apply',
  mcpApprovePlan: 'Approve plan',
  mcpRejectPlan: 'Reject plan',
  mcpApplyBoundary: 'Apply requires a fresh approval, matching plan/config/observation hashes, CAS-protected writes, backup, reload, and verification. Manual, blocked, auth-required, and unsupported actions are never executed.',
  mcpApplyControls: 'MCP apply controls',
  mcpApplyPreview: 'Apply preview',
  mcpApplyPreviewDetail: '{{count}} executable action(s); blocked/manual/auth/unsupported actions remain skipped.',
  mcpConfirmHighRisk: 'I confirm high-risk MCP configuration changes for this approved plan.',
  mcpApplying: 'Applying…',
  mcpApplyApprovedPlan: 'Apply approved plan',
  mcpApplyNeedsApproval: 'Approval must be current before apply is available.',
  mcpApplyStale: 'Approval is stale; regenerate and approve a fresh plan.',
  mcpPreflight: 'Preflight',
  mcpApplyRun: 'Apply run',
  mcpApplyRunDescription: 'Persisted action, reload, verify, backup, and rollback status for this apply attempt.',
  mcpApplyRunId: 'Run',
  mcpApplyStatus: 'Apply status',
  mcpApplyActions: 'Action status',
  mcpReloadAndVerify: 'Reload and verify',
  mcpVerify: 'Verify',
  mcpRollback: 'Rollback',
  mcpRollingBack: 'Rolling back…',
  mcpRollbackStatus: 'Rollback status',
  mcpAttempt: 'Attempt',
  mcpRecoveryRequired: 'Recovery required',
  mcpManualRecovery: 'Record manual recovery',
  mcpRecordingRecovery: 'Recording recovery…',
  mcpJournal: 'Durable journal',
  mcpNoPlan: 'Generate a dry-run plan to preview actions and approval state.',
  dismiss: 'Dismiss',
  close: 'Close',
  refresh: 'Refresh',
  channelsAndRuntimes: 'Channels and runtimes',
  channels: 'Channels',
  channelsNav: 'Channels',
  noChannels: 'Create a channel to open your first local workspace.',
  newChannel: 'New channel',
  channelPlaceholder: 'product-loop',
  channelDescriptionPlaceholder: 'What belongs in this Channel',
  channelGoal: 'Goal',
  channelGoalPlaceholder: 'The durable outcome this Channel is organizing',
  add: 'Add',
  runtimes: 'Local runtimes',
  installed: 'installed',
  unavailable: 'unavailable',
  noRuntimes: 'No runtime catalog is configured.',
  conversation: 'Channel conversation',
  localChannel: 'LOCAL CHANNEL',
  chooseChannel: 'Choose a channel',
  agentCount: '{{count}} agent',
  agentCountPlural: '{{count}} agents',
  createChannel: 'Create a channel',
  createChannelDescription: 'Your channels, agents, and message history stay in the local SQLite database.',
  loadingMessages: 'Loading message history…',
  startTask: 'Start a real task',
  startTaskDescription: 'Add an installed runtime agent, then send a concrete prompt from the composer below.',
  you: 'you',
  agent: 'agent',
  taskFor: 'Task for #{{channel}}',
  selectChannelFirst: 'Select a channel first',
  taskPlaceholder: 'Describe the task, constraints, and expected result…',
  runningAgentsHint: 'Running agents will receive this task.',
  noRunningAgentHint: 'Add or start an agent before sending.',
  running: 'Running…',
  runTask: 'Run task',
  channelAgents: 'Channel agents',
  agents: 'Agents',
  runtime: 'runtime',
  model: 'model',
  state: 'state',
  defaultModel: 'default',
  stopDelivery: 'Stop delivery',
  startAgent: 'Start agent',
  pauseAgent: 'Pause Agent',
  resumeAgent: 'Resume Agent',
  noAgents: 'No agent is attached to this channel yet.',
  addAgent: 'Add agent',
  name: 'Name',
  agentPlaceholder: 'builder',
  runtimeLabel: 'Runtime',
  noRuntimeInstalled: 'No runtime installed',
  modelLabel: 'Model',
  runtimeDefault: 'runtime default',
  adding: 'Adding…',
  addRunningAgent: 'Add running agent',
  language: 'Language',
  appearance: 'Appearance',
  lightMode: 'Light',
  darkMode: 'Dark',
  selectOption: 'Select an option',
  tasksEyebrow: 'LOCAL EXECUTION PLAN',
  tasksTitle: 'Task board',
  tasksDescription: 'Plan channel work, assign local Agents, track progress, and keep dependencies explicit.',
  tasksChannel: 'Channel',
  tasksSelectChannel: 'Select a channel',
  tasksFilter: 'Filter tasks',
  tasksFilterPlaceholder: 'Number, title, status, progress, or assignee',
  tasksView: 'Task view',
  tasksBoardView: 'Board',
  tasksListView: 'List',
  tasksNewTask: 'New task',
  tasksTitlePlaceholder: 'Describe a concrete deliverable',
  tasksCreating: 'Creating…',
  tasksCreate: 'Create task',
  tasksNoChannel: 'Create a channel first',
  tasksNoChannelDescription: 'Tasks are scoped to one local conversation channel.',
  tasksLoading: 'Loading channel tasks and dependencies…',
  tasksEmpty: 'No tasks yet',
  tasksEmptyDescription: 'Create the first task to make the local execution plan visible.',
  tasksNoMatches: 'No matching tasks',
  tasksNoMatchesDescription: 'Clear or change the filter to show other channel tasks.',
  tasksNoStatusTasks: 'No tasks in this state',
  tasksUnassigned: 'unassigned',
  tasksBlockedBy: 'blocked by #{{tasks}}',
  tasksDetail: 'Task detail',
  tasksStatus: 'Status',
  tasksStatusTodo: 'Todo',
  tasksStatusInProgress: 'In progress',
  tasksStatusInReview: 'In review',
  tasksStatusDone: 'Done',
  tasksAssignee: 'Assignee',
  tasksUnclaim: 'Unclaim',
  tasksSelectAgent: 'Select an Agent',
  tasksClaim: 'Claim task',
  tasksNoAgents: 'Add an Agent to this channel before assigning work.',
  tasksProgress: 'Progress',
  tasksProgressPlaceholder: 'Record the latest result, blocker, or next step.',
  tasksSaveProgress: 'Save progress',
  tasksDependencies: 'Dependencies',
  tasksUnknownDependency: 'Unknown task',
  tasksRemoveDependency: 'Remove dependency #{{task}}',
  tasksSelectDependency: 'Select a prerequisite',
  tasksAddDependency: 'Add dependency',
  tasksCreated: 'Created',
  tasksLoadError: 'Unable to load local tasks.',
  tasksActionError: 'Task operation failed.',
  knowledgeEyebrow: 'LOCAL KNOWLEDGE LAYER',
  knowledgeTitle: 'Knowledge workspace',
  knowledgeDescription: 'Maintain private and shared Agent memory for durable task continuity.',
  knowledgeView: 'Knowledge view',
  knowledgeMemory: 'Memory',
  memoryAgent: 'Agent',
  memoryChannel: 'Channel',
  memorySelectAgent: 'Select an Agent',
  memoryScope: 'Memory scope',
  memoryPrivate: 'Private L1',
  memoryShared: 'Channel L2',
  memoryPrivateDescription: 'Private durable context for {{agent}}.',
  memorySharedDescription: 'Shared durable context for #{{channel}}.',
  memoryFilter: 'Filter memory',
  memoryFilterPlaceholder: 'Topic, type, or content',
  memoryType: 'Memory type',
  memoryAllTypes: 'All types',
  memoryTypeProject: 'Project',
  memoryTypeUser: 'User',
  memoryTypeFeedback: 'Feedback',
  memoryTypeReference: 'Reference',
  memoryNewTopic: 'New topic',
  memoryTopic: 'Topic slug',
  memoryTopicPlaceholder: 'local_product_loop',
  memoryDescription: 'Description',
  memoryDescriptionPlaceholder: 'One-line summary',
  memoryBody: 'Markdown body',
  memoryBodyPlaceholder: 'Record durable facts, decisions, and constraints…',
  memoryCreating: 'Creating…',
  memoryCreate: 'Create topic',
  memoryTopics: 'Memory topics',
  memoryLoading: 'Loading durable memory…',
  memoryEmpty: 'No memory topics in this scope.',
  memoryNoMatches: 'No matching memory topics.',
  memoryNoAgent: 'Add an Agent first',
  memoryNoAgentDescription: 'Memory is namespaced through an Agent identity and its channel membership.',
  memorySelectTopic: 'Select a memory topic',
  memorySelectTopicDescription: 'Choose a durable topic from the left, or create one in the current scope.',
  memoryMoveToChannel: 'Move to channel',
  memoryMoveToAgent: 'Move to Agent',
  memorySaving: 'Saving…',
  memorySave: 'Save memory',
  memoryLoadError: 'Unable to load local memory.',
  memoryActionError: 'Memory operation failed.',
  historyEyebrow: 'LOCAL RUNTIME OBSERVABILITY',
  historyTitle: 'Runtime history',
  historyDescription: 'Inspect durable sessions, turns, token usage, structured trajectories, and activity from local Agents.',
  historyAgent: 'Agent',
  historySelectAgent: 'Select an Agent',
  historySessions: 'Sessions',
  historyTurns: 'Turns',
  historyTurnsLower: 'turns',
  historyOutputTokens: 'output tokens',
  historyCost: 'Cost',
  historyLocalUsage: 'recorded local usage',
  historyResets: 'Resets',
  historyContextResets: 'context resets',
  historyOneActive: '1 active now',
  historyNoneActive: 'none active',
  historyView: 'History view',
  historyActivity: 'Activity',
  historyFilterActivity: 'Filter activity',
  historyFilterPlaceholder: 'Activity, detail, trajectory, or session',
  historyLoading: 'Loading durable runtime history…',
  historyEmptySessions: 'No runtime sessions have been recorded for this Agent.',
  historySelectSession: 'Select a session to inspect its completed turns.',
  historySession: 'Runtime session',
  historyInput: 'Input',
  historyOutput: 'Output',
  historyContext: 'context',
  historyLoadingTurns: 'Loading structured turns…',
  historyEmptyTurns: 'No completed turns were recorded in this session.',
  historyTurnNumber: 'Turn #{{number}}',
  historyNoTrajectory: 'No structured trajectory entries were recorded.',
  historyOpenMessage: 'Open source message #{{seq}}',
  historyEmptyActivity: 'No activity markers have been recorded.',
  historyNoMatches: 'No activity entries match this filter.',
  historyNoAgent: 'Add an Agent first',
  historyNoAgentDescription: 'Runtime history is persisted per Agent after local execution begins.',
  historyActive: 'Active',
  historyCompleted: 'Completed',
  historyContextReset: 'Context reset',
  historyStopped: 'Stopped',
  historyError: 'Error',
  historyIdle: 'Idle',
  historyToolCall: 'Tool call',
  historyToolResult: 'Tool result',
  historyToolError: 'Tool error',
  historyThinking: 'Thinking',
  historyWarning: 'Warning',
  historyStatus: 'Status',
  historyLoadError: 'Unable to load local runtime history.',
  skillsEyebrow: 'LOCAL CAPABILITY REGISTRY',
  skillsTitle: 'Skills workspace',
  skillsDescription: 'Import reusable skill folders once, then install them atomically into any local Agent workspace.',
  skillsInventoryTitle: 'Runtime × Skill inventory',
  skillsInventoryDescription: 'Read-only discovery and doctor results across local Agent runtimes.',
  skillsEvidenceNotice: 'Evidence labels distinguish filesystem candidates from native runtime discovery. Neither proves that a running session loaded or activated a skill.',
  skillsRuntime: 'Runtime',
  skillsCompatibility: 'Compatibility',
  skillsAgents: 'Agents',
  skillsDiscovered: 'Skills',
  skillsIssues: 'Issues',
  skillsEvidence: 'Evidence',
  skillsNoEvidence: 'not inspected',
  skillsDoctorOk: 'healthy',
  skillsDoctorWarning: 'needs review',
  skillsDoctorError: 'issues found',
  skillsAgentDoctor: '{{agent}} doctor details',
  skillsSearchPaths: 'Search paths',
  skillsPathReady: 'readable',
  skillsPathUnavailable: 'missing or unreadable',
  skillsSymlink: 'symlink',
  skillsDisabled: 'disabled by runtime',
  skillsNoIssues: 'No filesystem or install-record issues found.',
  skillsCatalog: 'Local catalog',
  skillsCatalogDescription: 'SQLite is the source of truth for imported skill snapshots.',
  skillsSource: 'Source URL or absolute path',
  skillsSourcePlaceholder: '/Users/me/skills/reviewer or https://github.com/org/repo.git',
  skillsSubpath: 'Subpath (optional)',
  skillsSubpathPlaceholder: 'skills/reviewer',
  skillsNameOverride: 'Name override (optional)',
  skillsNamePlaceholder: 'reviewer',
  skillsImport: 'Import skill',
  skillsImporting: 'Importing…',
  skillsLoadingCatalog: 'Loading local skill catalog…',
  skillsEmptyCatalog: 'No skills imported',
  skillsEmptyCatalogDescription: 'Import a folder with SKILL.md to build the reusable local catalog.',
  skillsNoDescription: 'No description in SKILL.md.',
  skillsFiles: 'Files',
  skillsSize: 'Size',
  skillsInUse: 'In use',
  skillsReinstall: 'Refresh',
  skillsInstall: 'Install',
  skillsInstalled: 'Installed',
  skillsDelete: 'Delete skill',
  skillsDeleteConfirm: 'Delete {{name}} from the local catalog and remove its managed installs?',
  skillsAgentWorkspace: 'Agent workspace',
  skillsAgentWorkspaceDescription: 'Compare runtime discovery with managed SQLite install records.',
  skillsAgent: 'Agent',
  skillsSelectAgent: 'Select an Agent',
  skillsCompatibilitySupported: 'supported',
  skillsCompatibilityUncertain: 'experimental',
  skillsCompatibilityUnsupported: 'unsupported',
  skillsCompatibilityUnknown: 'unknown',
  skillsNoAgent: 'Add an Agent first',
  skillsNoAgentDescription: 'Skills are installed into a specific local Agent workspace.',
  skillsLoadingAgent: 'Scanning runtime skill paths…',
  skillsEmptyAgent: 'No skills discovered',
  skillsEmptyAgentDescription: 'Import a catalog entry and install it, or add a runtime-native skill on disk.',
  skillsFilter: 'Filter Agent skills',
  skillsFilterPlaceholder: 'Name, state, type, or description',
  skillsNoMatches: 'No matching skills',
  skillsNoMatchesDescription: 'Clear or change the filter to show other discovered skills.',
  skillsViewFiles: 'View files',
  skillsRemoveRecord: 'Remove record',
  skillsUninstall: 'Uninstall',
  skillsFileBrowser: 'INSTALLED FILES',
  skillsBinaryFile: 'Binary file preview is not available.',
  skillsSelectFile: 'Select a text file to preview.',
  skillsSelectedLibrary: 'Selected catalog entry',
  skillsInstallTo: 'Install to {{agent}}',
  skillsLoadError: 'Unable to load local skills.',
  skillsActionError: 'Skill operation failed.',
}

const chinese: Record<keyof typeof english, string> = {
  loading: '正在启动本地工作区…',
  brand: 'cocli 本地',
  serviceOnline: 'SQLite + HTTP 已连接',
  liveConnected: '实时执行流已连接',
  liveReconnecting: '实时执行流重连中',
  onboardingEyebrow: '首次使用',
  onboardingTitle: '配置第一个本地任务',
  onboardingDescription: 'cocli 连接本地运行时、频道与 Agent，但不替代 Agent 自身的决策。',
  onboardingRuntime: '检测到已安装的运行时',
  onboardingChannel: '创建或选择一个频道',
  onboardingAgent: '向当前频道添加 Agent',
  onboardingTask: '发送第一个明确任务',
  liveRunning: '实时执行',
  liveLimited: '触发限额',
  liveError: '执行错误',
  liveTool: '工具',
  liveCancel: '取消本轮',
  liveCancelling: '取消中…',
  search: '搜索',
  searching: '搜索中…',
  globalSearchEyebrow: '本地索引',
  globalSearch: '全局搜索',
  globalSearchPlaceholder: '搜索频道、Agent、消息和任务…',
  globalSearchEmpty: '没有匹配的本地结果。',
  downloadBackup: '下载应用状态备份',
  workspaceNavigation: '工作区导航',
  channelWorkspace: '频道工作区',
  agentWorkspace: 'Agent 工作区',
  agentOverview: 'Agent 概览',
  agentSelect: '选择 Agent',
  agentDirect: '直接对话',
  agentNoMessages: '向这个 Agent 提出需求，开始持久化工作。',
  agentDirectPlaceholder: '描述交给这个 Agent 的需求…',
  currentWork: '当前工作',
  agentIdle: '当前没有工作锚点。',
  nextStep: '下一步',
  memberChannels: '参与频道',
  workspaceAttachments: 'Workspace 载体',
  noWorkspaces: '尚未绑定可选 Workspace。',
  workspaceKind: 'Workspace 类型',
  workspaceDirectory: '目录',
  workspaceGit: 'Git 仓库',
  workspaceExternal: '外部引用',
  workspaceManaged: '托管 Workspace',
  workspaceLocator: 'Workspace 位置',
  channelWorkspaceLocator: 'Channel Workspace 位置',
  workspaceLocatorPlaceholder: '路径、仓库或外部引用',
  attachWorkspace: '挂载 Workspace',
  operationHistory: 'Agent 创建记录',
  noOperations: '还没有自组织操作记录。',
  lifecycle: '生命周期',
  diagnostics: '诊断',
  createStandaloneAgent: '创建持久 Agent',
  description: '描述',
  instructions: '持久化指令',
  agentDescriptionPlaceholder: '这个 Agent 负责什么',
  agentInstructionsPlaceholder: '这个 Agent 应长期遵循的工作方式',
  settings: '设置',
  runtimeSettings: '运行时设置',
  runtimeSettingsDescription: '运行时可用性、版本和能力属于底层执行细节。',
  chatWorkspace: '对话',
  tasksWorkspace: '任务',
  knowledgeWorkspace: '知识',
  historyWorkspace: '历史',
  skillsWorkspace: 'Skills',
  mcpWorkspace: 'MCP',
  mcpEyebrow: '只读治理',
  mcpTitle: 'MCP 清单与诊断',
  mcpDescription: '对照 MCP 配置与 Runtime 原生证据，全程不修改本机配置。',
  mcpLoading: '正在探测本机 Runtime MCP 状态…',
  mcpLoadError: '无法读取本机 MCP 状态。',
  mcpDoctorStatus: '诊断状态',
  mcpServers: '服务器',
  mcpObservations: '观测',
  mcpFindings: '诊断项',
  mcpMatrix: 'Runtime × Server 状态矩阵',
  mcpMatrixDescription: 'D 可发现 · C 已配置 · L 已加载 · E 已启用 · P 已批准 · A 已认证 · H 健康 · S 当前会话可见 · I 已调用。点号表示未知，而不是否。',
  mcpRuntime: 'Runtime',
  mcpNotObserved: '该 Runtime 与服务器尚无观测。',
  mcpEvidence: '证据与观测时间',
  mcpEvidenceDescription: 'Runtime 原生 CLI/app-server 证据与文件系统配置发现严格区分。',
  mcpNoFindings: '未发现 MCP 诊断问题。',
  mcpZeroWriteNotice: 'Phase 2C 只会通过协商后的 adapter、隔离 writer、持久 journal 恢复和 fresh verify 执行有效 approval，且不会重启活跃 Runtime 会话。',
  mcpCapabilities: 'Runtime adapter 能力',
  mcpCapabilitiesDescription: '版本化 adapter contract 会在 plan approve/apply 前说明 read/write/reload/verify 支持边界。',
  mcpCapabilityHash: 'Capability hash',
  mcpAdapter: 'Adapter',
  mcpBinaryVersion: 'Binary/schema 版本',
  mcpReloadStrategy: 'Reload 策略',
  mcpDestination: '写入目标',
  mcpOperations: '操作能力',
  mcpNoCapabilities: '暂无 Runtime adapter 能力报告。',
  mcpProfiles: 'Profiles',
  mcpProfilesDescription: '绑定到 machine、Workspace 或 Agent 目标的版本化期望状态。',
  mcpNoProfiles: '尚未定义 MCP profile。',
  mcpProfileServers: '个服务器',
  mcpNoBindings: '无目标绑定',
  mcpDesiredEnabled: '期望启用',
  mcpDesiredDisabled: '期望禁用',
  mcpEffectiveDesired: '生效期望状态',
  mcpEffectiveDescription: '展示该目标的 profile 继承、冲突与最终绑定。',
  mcpEffectiveTarget: '目标',
  mcpConflicts: '冲突',
  mcpHighRiskContext: '高风险上下文',
  mcpStandardContext: '标准上下文',
  mcpAppliedResolution: '已应用',
  mcpSkippedResolution: '已跳过',
  mcpNoEffectiveDesired: '暂无生效期望状态。',
  mcpPlanPreview: '计划预览',
  mcpPlanDescription: '在 Runtime writer 触碰隔离配置源之前，预览已批准的 apply 契约。',
  mcpPlanning: '生成中…',
  mcpGeneratePlan: '生成 dry-run 计划',
  mcpPlanError: 'MCP 计划操作失败。',
  mcpApplyError: 'MCP apply 操作失败。',
  mcpRollbackError: 'MCP rollback 操作失败。',
  mcpApprovalStatus: 'Approval 状态',
  mcpApprovalExpires: 'Approval 到期时间',
  mcpPlanHash: 'Plan hash',
  mcpDryRun: 'dry-run',
  mcpNotDryRun: '非 dry-run',
  mcpApprovedNotApplied: '已批准但未应用',
  mcpBlocked: '已阻塞',
  mcpBefore: '变更前',
  mcpAfter: '变更后',
  mcpExpectedHashes: '期望 source/schema hash',
  mcpExecution: '执行',
  mcpExecutableAction: '可执行 apply',
  mcpNonExecutableAction: 'apply 不会执行',
  mcpApprovePlan: '批准计划',
  mcpRejectPlan: '拒绝计划',
  mcpApplyBoundary: 'Apply 必须具备新鲜 approval、匹配的 plan/config/observation hash、CAS 写入、备份、reload 与 verify。manual、blocked、auth-required 和 unsupported action 永不执行。',
  mcpApplyControls: 'MCP apply 控件',
  mcpApplyPreview: 'Apply 预览',
  mcpApplyPreviewDetail: '{{count}} 个可执行 action；blocked/manual/auth/unsupported action 将保持跳过。',
  mcpConfirmHighRisk: '我确认对该已批准计划执行高风险 MCP 配置变更。',
  mcpApplying: '应用中…',
  mcpApplyApprovedPlan: '应用已批准计划',
  mcpApplyNeedsApproval: '需要当前有效 approval 才能 apply。',
  mcpApplyStale: 'Approval 已 stale；请重新生成并批准计划。',
  mcpPreflight: 'Preflight',
  mcpApplyRun: 'Apply run',
  mcpApplyRunDescription: '本次 apply 的 action、reload、verify、backup 与 rollback 状态均已持久化。',
  mcpApplyRunId: 'Run',
  mcpApplyStatus: 'Apply 状态',
  mcpApplyActions: 'Action 状态',
  mcpReloadAndVerify: 'Reload 与 verify',
  mcpVerify: 'Verify',
  mcpRollback: '回滚',
  mcpRollingBack: '回滚中…',
  mcpRollbackStatus: '回滚状态',
  mcpAttempt: '尝试次数',
  mcpRecoveryRequired: '需要恢复',
  mcpManualRecovery: '记录人工恢复',
  mcpRecordingRecovery: '正在记录恢复…',
  mcpJournal: '持久 journal',
  mcpNoPlan: '生成 dry-run 计划以预览 action 和 approval 状态。',
  dismiss: '关闭',
  close: '关闭',
  refresh: '刷新',
  channelsAndRuntimes: '频道与运行时',
  channels: '频道',
  channelsNav: '频道',
  noChannels: '创建一个频道，开启首个本地工作区。',
  newChannel: '新建频道',
  channelPlaceholder: 'product-loop',
  channelDescriptionPlaceholder: '这个 Channel 用来组织什么',
  channelGoal: '目标',
  channelGoalPlaceholder: '这个 Channel 要持续推动的结果',
  add: '添加',
  runtimes: '本地运行时',
  installed: '已安装',
  unavailable: '不可用',
  noRuntimes: '尚未配置运行时目录。',
  conversation: '频道对话',
  localChannel: '本地频道',
  chooseChannel: '选择一个频道',
  agentCount: '{{count}} 个 Agent',
  agentCountPlural: '{{count}} 个 Agent',
  createChannel: '创建频道',
  createChannelDescription: '频道、Agent 和消息记录会保存在本机 SQLite 数据库中。',
  loadingMessages: '正在加载消息记录…',
  startTask: '开始真实任务',
  startTaskDescription: '添加一个已安装的运行时 Agent，然后在下方输入明确任务。',
  you: '你',
  agent: 'Agent',
  taskFor: '#{{channel}} 的任务',
  selectChannelFirst: '请先选择频道',
  taskPlaceholder: '描述任务、约束条件和预期结果…',
  runningAgentsHint: '运行中的 Agent 将收到此任务。',
  noRunningAgentHint: '请先添加或启动一个 Agent。',
  running: '执行中…',
  runTask: '运行任务',
  channelAgents: '频道 Agent',
  agents: 'Agent',
  runtime: '运行时',
  model: '模型',
  state: '状态',
  defaultModel: '默认',
  stopDelivery: '停止接收',
  startAgent: '启动 Agent',
  pauseAgent: '暂停 Agent',
  resumeAgent: '恢复 Agent',
  noAgents: '此频道还没有关联 Agent。',
  addAgent: '添加 Agent',
  name: '名称',
  agentPlaceholder: 'builder',
  runtimeLabel: '运行时',
  noRuntimeInstalled: '没有已安装的运行时',
  modelLabel: '模型',
  runtimeDefault: '运行时默认值',
  adding: '添加中…',
  addRunningAgent: '添加并启动 Agent',
  language: '语言',
  appearance: '外观',
  lightMode: '亮色',
  darkMode: '暗色',
  selectOption: '选择一个选项',
  tasksEyebrow: '本地执行计划',
  tasksTitle: '任务看板',
  tasksDescription: '规划频道工作、分配本地 Agent、记录进度，并明确维护任务依赖。',
  tasksChannel: '频道',
  tasksSelectChannel: '选择频道',
  tasksFilter: '筛选任务',
  tasksFilterPlaceholder: '编号、标题、状态、进度或负责人',
  tasksView: '任务视图',
  tasksBoardView: '看板',
  tasksListView: '列表',
  tasksNewTask: '新建任务',
  tasksTitlePlaceholder: '描述一个明确的交付结果',
  tasksCreating: '创建中…',
  tasksCreate: '创建任务',
  tasksNoChannel: '请先创建频道',
  tasksNoChannelDescription: '任务归属于一个本地对话频道。',
  tasksLoading: '正在加载频道任务与依赖…',
  tasksEmpty: '还没有任务',
  tasksEmptyDescription: '创建首个任务，让本地执行计划清晰可见。',
  tasksNoMatches: '没有匹配的任务',
  tasksNoMatchesDescription: '清空或调整筛选条件以查看其他频道任务。',
  tasksNoStatusTasks: '此状态下没有任务',
  tasksUnassigned: '未分配',
  tasksBlockedBy: '被 #{{tasks}} 阻塞',
  tasksDetail: '任务详情',
  tasksStatus: '状态',
  tasksStatusTodo: '待办',
  tasksStatusInProgress: '进行中',
  tasksStatusInReview: '审核中',
  tasksStatusDone: '完成',
  tasksAssignee: '负责人',
  tasksUnclaim: '取消认领',
  tasksSelectAgent: '选择 Agent',
  tasksClaim: '认领任务',
  tasksNoAgents: '请先向此频道添加 Agent，再分配任务。',
  tasksProgress: '进度',
  tasksProgressPlaceholder: '记录最新结果、阻塞项或下一步。',
  tasksSaveProgress: '保存进度',
  tasksDependencies: '依赖任务',
  tasksUnknownDependency: '未知任务',
  tasksRemoveDependency: '移除依赖 #{{task}}',
  tasksSelectDependency: '选择前置任务',
  tasksAddDependency: '添加依赖',
  tasksCreated: '创建时间',
  tasksLoadError: '无法加载本地任务。',
  tasksActionError: '任务操作失败。',
  knowledgeEyebrow: '本地知识层',
  knowledgeTitle: '知识工作区',
  knowledgeDescription: '维护 Agent 私有/频道共享记忆，支撑任务连续性。',
  knowledgeView: '知识视图',
  knowledgeMemory: '记忆',
  memoryAgent: 'Agent',
  memoryChannel: 'Channel',
  memorySelectAgent: '选择 Agent',
  memoryScope: '记忆作用域',
  memoryPrivate: '私有 L1',
  memoryShared: '频道 L2',
  memoryPrivateDescription: '{{agent}} 的私有持久化上下文。',
  memorySharedDescription: '#{{channel}} 的共享持久化上下文。',
  memoryFilter: '筛选记忆',
  memoryFilterPlaceholder: '主题、类型或内容',
  memoryType: '记忆类型',
  memoryAllTypes: '全部类型',
  memoryTypeProject: '项目',
  memoryTypeUser: '用户',
  memoryTypeFeedback: '反馈',
  memoryTypeReference: '参考',
  memoryNewTopic: '新建主题',
  memoryTopic: '主题标识',
  memoryTopicPlaceholder: 'local_product_loop',
  memoryDescription: '描述',
  memoryDescriptionPlaceholder: '单行摘要',
  memoryBody: 'Markdown 正文',
  memoryBodyPlaceholder: '记录需要长期保留的事实、决策和约束…',
  memoryCreating: '创建中…',
  memoryCreate: '创建主题',
  memoryTopics: '记忆主题',
  memoryLoading: '正在加载持久化记忆…',
  memoryEmpty: '此作用域还没有记忆主题。',
  memoryNoMatches: '没有匹配的记忆主题。',
  memoryNoAgent: '请先添加 Agent',
  memoryNoAgentDescription: '记忆通过 Agent 身份及其频道成员关系划分命名空间。',
  memorySelectTopic: '选择记忆主题',
  memorySelectTopicDescription: '从左侧选择持久化主题，或在当前作用域创建一个。',
  memoryMoveToChannel: '移动到频道',
  memoryMoveToAgent: '移动到 Agent',
  memorySaving: '保存中…',
  memorySave: '保存记忆',
  memoryLoadError: '无法加载本地记忆。',
  memoryActionError: '记忆操作失败。',
  historyEyebrow: '本地运行时可观测性',
  historyTitle: '运行历史',
  historyDescription: '查看本地 Agent 的持久化会话、轮次、Token 用量、结构化轨迹与活动记录。',
  historyAgent: 'Agent',
  historySelectAgent: '选择 Agent',
  historySessions: '会话',
  historyTurns: '轮次',
  historyTurnsLower: '轮',
  historyOutputTokens: '输出 Token',
  historyCost: '成本',
  historyLocalUsage: '已记录的本地用量',
  historyResets: '重置',
  historyContextResets: '上下文重置',
  historyOneActive: '当前 1 个活跃',
  historyNoneActive: '当前无活跃',
  historyView: '历史视图',
  historyActivity: '活动',
  historyFilterActivity: '筛选活动',
  historyFilterPlaceholder: '活动、详情、轨迹或会话',
  historyLoading: '正在加载持久化运行历史…',
  historyEmptySessions: '此 Agent 尚未记录运行时会话。',
  historySelectSession: '选择一个会话，查看其已完成轮次。',
  historySession: '运行时会话',
  historyInput: '输入',
  historyOutput: '输出',
  historyContext: '上下文',
  historyLoadingTurns: '正在加载结构化轮次…',
  historyEmptyTurns: '此会话没有已完成的轮次记录。',
  historyTurnNumber: '第 {{number}} 轮',
  historyNoTrajectory: '没有记录结构化轨迹条目。',
  historyOpenMessage: '打开来源消息 #{{seq}}',
  historyEmptyActivity: '还没有活动记录。',
  historyNoMatches: '没有匹配此筛选条件的活动。',
  historyNoAgent: '请先添加 Agent',
  historyNoAgentDescription: '本地执行开始后，运行历史会按 Agent 持久化。',
  historyActive: '活跃',
  historyCompleted: '已完成',
  historyContextReset: '上下文重置',
  historyStopped: '已停止',
  historyError: '错误',
  historyIdle: '空闲',
  historyToolCall: '工具调用',
  historyToolResult: '工具结果',
  historyToolError: '工具错误',
  historyThinking: '思考',
  historyWarning: '警告',
  historyStatus: '状态',
  historyLoadError: '无法加载本地运行历史。',
  skillsEyebrow: '本地能力目录',
  skillsTitle: 'Skills 工作区',
  skillsDescription: 'Skill 目录只需导入一次，即可原子安装到任意本地 Agent 工作区。',
  skillsInventoryTitle: 'Runtime × Skill 清单',
  skillsInventoryDescription: '汇总本地 Agent 运行时的只读发现结果与 doctor 诊断。',
  skillsEvidenceNotice: '证据标签会区分文件系统候选项与运行时原生发现；两者都不代表当前会话已加载或激活 Skill。',
  skillsRuntime: '运行时',
  skillsCompatibility: '兼容性',
  skillsAgents: 'Agent',
  skillsDiscovered: 'Skill',
  skillsIssues: '问题',
  skillsEvidence: '证据',
  skillsNoEvidence: '尚未检查',
  skillsDoctorOk: '正常',
  skillsDoctorWarning: '需要检查',
  skillsDoctorError: '发现问题',
  skillsAgentDoctor: '{{agent}} doctor 详情',
  skillsSearchPaths: '搜索路径',
  skillsPathReady: '可读取',
  skillsPathUnavailable: '不存在或不可读取',
  skillsSymlink: '符号链接',
  skillsDisabled: '运行时已禁用',
  skillsNoIssues: '未发现文件系统或安装记录问题。',
  skillsCatalog: '本地目录',
  skillsCatalogDescription: 'SQLite 保存导入 Skill 的权威快照。',
  skillsSource: '来源 URL 或绝对路径',
  skillsSourcePlaceholder: '/Users/me/skills/reviewer 或 https://github.com/org/repo.git',
  skillsSubpath: '子目录（可选）',
  skillsSubpathPlaceholder: 'skills/reviewer',
  skillsNameOverride: '名称覆盖（可选）',
  skillsNamePlaceholder: 'reviewer',
  skillsImport: '导入 Skill',
  skillsImporting: '导入中…',
  skillsLoadingCatalog: '正在加载本地 Skill 目录…',
  skillsEmptyCatalog: '尚未导入 Skill',
  skillsEmptyCatalogDescription: '导入包含 SKILL.md 的目录，建立可复用的本地能力目录。',
  skillsNoDescription: 'SKILL.md 中没有描述。',
  skillsFiles: '文件',
  skillsSize: '大小',
  skillsInUse: '使用中',
  skillsReinstall: '刷新',
  skillsInstall: '安装',
  skillsInstalled: '已安装',
  skillsDelete: '删除 Skill',
  skillsDeleteConfirm: '从本地目录删除 {{name}}，并移除其受管安装吗？',
  skillsAgentWorkspace: 'Agent 工作区',
  skillsAgentWorkspaceDescription: '对照运行时扫描结果与 SQLite 受管安装记录。',
  skillsAgent: 'Agent',
  skillsSelectAgent: '选择 Agent',
  skillsCompatibilitySupported: '支持',
  skillsCompatibilityUncertain: '实验性',
  skillsCompatibilityUnsupported: '不支持',
  skillsCompatibilityUnknown: '未知',
  skillsNoAgent: '请先添加 Agent',
  skillsNoAgentDescription: 'Skill 会安装到指定的本地 Agent 工作区。',
  skillsLoadingAgent: '正在扫描运行时 Skill 路径…',
  skillsEmptyAgent: '未发现 Skill',
  skillsEmptyAgentDescription: '可导入目录条目并安装，或直接在磁盘添加运行时原生 Skill。',
  skillsFilter: '筛选 Agent Skills',
  skillsFilterPlaceholder: '名称、状态、类型或描述',
  skillsNoMatches: '没有匹配的 Skill',
  skillsNoMatchesDescription: '清空或调整筛选条件以查看其他已发现的 Skill。',
  skillsViewFiles: '查看文件',
  skillsRemoveRecord: '移除记录',
  skillsUninstall: '卸载',
  skillsFileBrowser: '已安装文件',
  skillsBinaryFile: '暂不支持预览二进制文件。',
  skillsSelectFile: '请选择一个文本文件进行预览。',
  skillsSelectedLibrary: '已选目录条目',
  skillsInstallTo: '安装到 {{agent}}',
  skillsLoadError: '无法加载本地 Skills。',
  skillsActionError: 'Skill 操作失败。',
}

const dictionaries = {
  en: english,
  'zh-CN': chinese,
}

export type LocalCopyKey = keyof typeof english

export function translate(
  language: LocalLanguage,
  key: LocalCopyKey,
  values: Record<string, string | number> = {},
): string {
  let copy: string = dictionaries[language][key]
  for (const [name, value] of Object.entries(values)) {
    copy = copy.replaceAll(`{{${name}}}`, String(value))
  }
  return copy
}

export function resolveInitialLanguage(): LocalLanguage {
  try {
    const stored = localStorage.getItem('cocli-local-language')
    if (stored === 'en' || stored === 'zh-CN') return stored
  } catch {
    // Storage can be unavailable in privacy-restricted environments.
  }
  return navigator.language.toLowerCase().startsWith('zh') ? 'zh-CN' : 'en'
}
